# Configuration/Services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    PrototypeIntegration\Forms\:
        resource: '../Classes/*'
        shared: false

    PrototypeIntegration\Forms\Field:
        public: true

    PrototypeIntegration\Forms\Form:
        public: true
